development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://0.0.0.0:9292/faye"
  secret_token: “batkaro”
  signature_expiration: 86400
